package antihackerman.backendapp.model;

public enum ExtensionType {
    AUTHORITY_KEY_IDENTIFIER, BASIC_CONSTRAINTS, KEY_USAGE, SUBJECT_KEY_IDENTIFIER, EXTENDED_KEY_USAGE, SUBJECT_ALTERNATIVE_NAME
}
