import antihackerman.model.*
import antihackerman.messaging.*
import java.util.ArrayList;

global ArrayList<DeviceAlarm> activatedAlarms;

rule "Is boolean alarm triggered - true"
	when
	  $device: Device(type == DeviceType.BOOLEAN_DEVICE)
	  $message: Message(value==1)
	  $alarm: DeviceAlarm(alarmForBool==true)
	then
		activatedAlarms.add($alarm);
	end

rule "Is boolean alarm triggered - false"
	when
	  $device: Device(type == DeviceType.BOOLEAN_DEVICE)
	  $message: Message(value==0)
	  $alarm: DeviceAlarm(alarmForBool==false)
	then
		activatedAlarms.add($alarm);
	end

rule "Is interval alarm triggered"
	when
	  $device: Device(type == DeviceType.INTERVAL_DEVICE)
	  $alarm: DeviceAlarm($borderMin: borderMin, $borderMax: borderMax)
      $message: Message(value > $borderMin && value < $borderMax)

	then
		activatedAlarms.add($alarm);
	end